#!/bin/bash

FORMAT=$(echo -e "\033[1;33m%w%f\033[0m written")
"$@"
#while inotifywait -e modify --format "$FORMAT" ~/bin/cpp/katas/single_List 
while inotifywait -e modify --format "$FORMAT" ../ 
do
	"$@"
done
